// TACO (Tabela Brasileira de Composição de Alimentos) via brolesi/taco (github.com/brolesi/taco), dados de NEPA/UNICAMP, MIT.
// Valores por 100 g da porção comestível. Curadoria de 51 alimentos comuns pra montar refeições simples.
export const foods = [
  { id: 3, name: "Arroz branco cozido", tag: "carb", kcal: 128, protein: 2.5, carbs: 28.1, fat: 0.2, fiber: 1.6, gluten: false, dairy: false },
  { id: 1, name: "Arroz integral cozido", tag: "carb", kcal: 124, protein: 2.6, carbs: 25.8, fat: 1, fiber: 2.7, gluten: false, dairy: false },
  { id: 7, name: "Aveia em flocos", tag: "carb", kcal: 394, protein: 13.9, carbs: 66.6, fat: 8.5, fiber: 9.1, gluten: true, dairy: false },
  { id: 89, name: "Batata doce cozida", tag: "carb", kcal: 118, protein: 1.3, carbs: 28.2, fat: 0.1, fiber: 2.6, gluten: false, dairy: false },
  { id: 91, name: "Batata inglesa cozida", tag: "carb", kcal: 52, protein: 1.2, carbs: 11.9, fat: 0, fiber: 1.3, gluten: false, dairy: false },
  { id: 533, name: "Cuscuz de milho", tag: "carb", kcal: 113, protein: 2.2, carbs: 25.3, fat: 0.7, fiber: 2.1, gluten: false, dairy: false },
  { id: 40, name: "Macarrão cru", tag: "carb", kcal: 371, protein: 10, carbs: 77.9, fat: 1.3, fiber: 2.9, gluten: true, dairy: false },
  { id: 129, name: "Mandioca cozida", tag: "carb", kcal: 125, protein: 0.6, carbs: 30.1, fat: 0.3, fiber: 1.6, gluten: false, dairy: false },
  { id: 52, name: "Pão de forma integral", tag: "carb", kcal: 253, protein: 9.4, carbs: 49.9, fat: 3.7, fiber: 6.9, gluten: true, dairy: false },
  { id: 53, name: "Pão francês", tag: "carb", kcal: 300, protein: 8, carbs: 58.6, fat: 3.1, fiber: 2.3, gluten: true, dairy: false },
  { id: 551, name: "Tapioca com manteiga", tag: "carb", kcal: 348, protein: 0.1, carbs: 63.6, fat: 10.9, fiber: 0, gluten: false, dairy: true },
  { id: 448, name: "Iogurte natural", tag: "dairy", kcal: 51, protein: 4.1, carbs: 1.9, fat: 3, fiber: 0, gluten: false, dairy: true },
  { id: 461, name: "Queijo minas frescal", tag: "dairy", kcal: 264, protein: 17.4, carbs: 3.2, fat: 20.2, fiber: 0, gluten: false, dairy: true },
  { id: 463, name: "Queijo muçarela", tag: "dairy", kcal: 330, protein: 22.6, carbs: 3, fat: 25.2, fiber: 0, gluten: false, dairy: true },
  { id: 468, name: "Requeijão cremoso", tag: "dairy", kcal: 257, protein: 9.6, carbs: 2.4, fat: 23.4, fiber: 0, gluten: false, dairy: true },
  { id: 260, name: "Azeite de oliva", tag: "fat", kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, gluten: false, dairy: false },
  { id: 262, name: "Manteiga", tag: "fat", kcal: 758, protein: 0.4, carbs: 0, fat: 86, fiber: 0, gluten: false, dairy: true },
  { id: 163, name: "Abacate", tag: "fruit", kcal: 96, protein: 1.2, carbs: 6, fat: 8.4, fiber: 6.3, gluten: false, dairy: false },
  { id: 164, name: "Abacaxi", tag: "fruit", kcal: 48, protein: 0.9, carbs: 12.3, fat: 0.1, fiber: 1, gluten: false, dairy: false },
  { id: 179, name: "Banana nanica", tag: "fruit", kcal: 92, protein: 1.4, carbs: 23.8, fat: 0.1, fiber: 1.9, gluten: false, dairy: false },
  { id: 208, name: "Laranja", tag: "fruit", kcal: 45, protein: 1, carbs: 11.5, fat: 0.1, fiber: 1.1, gluten: false, dairy: false },
  { id: 222, name: "Maçã Fuji", tag: "fruit", kcal: 56, protein: 0.3, carbs: 15.2, fat: 0, fiber: 1.3, gluten: false, dairy: false },
  { id: 226, name: "Mamão papaia", tag: "fruit", kcal: 40, protein: 0.5, carbs: 10.4, fat: 0.1, fiber: 1, gluten: false, dairy: false },
  { id: 235, name: "Melancia", tag: "fruit", kcal: 33, protein: 0.9, carbs: 8.1, fat: 0, fiber: 0.1, gluten: false, dairy: false },
  { id: 239, name: "Morango", tag: "fruit", kcal: 30, protein: 0.9, carbs: 6.8, fat: 0.3, fiber: 1.7, gluten: false, dairy: false },
  { id: 561, name: "Feijão carioca cozido", tag: "legume", kcal: 76, protein: 4.8, carbs: 13.6, fat: 0.5, fiber: 8.5, gluten: false, dairy: false },
  { id: 567, name: "Feijão preto cozido", tag: "legume", kcal: 77, protein: 4.5, carbs: 14, fat: 0.5, fiber: 8.4, gluten: false, dairy: false },
  { id: 557, name: "Amendoim cru", tag: "nut", kcal: 544, protein: 27.2, carbs: 20.3, fat: 43.9, fiber: 8, gluten: false, dairy: false },
  { id: 588, name: "Castanha de caju", tag: "nut", kcal: 570, protein: 18.5, carbs: 29.1, fat: 46.3, fiber: 3.7, gluten: false, dairy: false },
  { id: 277, name: "Atum em conserva", tag: "protein", kcal: 166, protein: 26.2, carbs: 0, fat: 6, fiber: 0, gluten: false, dairy: false },
  { id: 328, name: "Carne moída (acém) cozida", tag: "protein", kcal: 215, protein: 27.3, carbs: 0, fat: 10.9, fiber: 0, gluten: false, dairy: false },
  { id: 306, name: "Filé de peixe empanado", tag: "protein", kcal: 283, protein: 21.4, carbs: 5, fat: 19.1, fiber: 0, gluten: false, dairy: false },
  { id: 416, name: "Hambúrguer bovino", tag: "protein", kcal: 258, protein: 20, carbs: 6.3, fat: 17, fiber: 0, gluten: false, dairy: false },
  { id: 488, name: "Ovo cozido", tag: "protein", kcal: 146, protein: 13.3, carbs: 0.6, fat: 9.5, fiber: 0, gluten: false, dairy: false },
  { id: 490, name: "Ovo frito", tag: "protein", kcal: 240, protein: 15.6, carbs: 1.2, fat: 18.6, fiber: 0, gluten: false, dairy: false },
  { id: 377, name: "Patinho grelhado", tag: "protein", kcal: 219, protein: 35.9, carbs: 0, fat: 7.3, fiber: 0, gluten: false, dairy: false },
  { id: 408, name: "Peito de frango cozido", tag: "protein", kcal: 163, protein: 31.5, carbs: 0, fat: 3.2, fiber: 0, gluten: false, dairy: false },
  { id: 410, name: "Peito de frango grelhado", tag: "protein", kcal: 159, protein: 32, carbs: 0, fat: 2.5, fiber: 0, gluten: false, dairy: false },
  { id: 438, name: "Presunto", tag: "protein", kcal: 128, protein: 14.4, carbs: 1.4, fat: 6.8, fiber: 0, gluten: false, dairy: false },
  { id: 491, name: "Achocolatado em pó", tag: "sweet", kcal: 401, protein: 4.2, carbs: 91.2, fat: 2.2, fiber: 3.9, gluten: false, dairy: false },
  { id: 495, name: "Chocolate ao leite", tag: "sweet", kcal: 540, protein: 7.2, carbs: 59.6, fat: 30.3, fiber: 2.2, gluten: false, dairy: true },
  { id: 71, name: "Abobrinha crua", tag: "veg", kcal: 19, protein: 1.1, carbs: 4.3, fat: 0.1, fiber: 1.4, gluten: false, dairy: false },
  { id: 77, name: "Alface", tag: "veg", kcal: 9, protein: 0.6, carbs: 1.7, fat: 0.1, fiber: 1, gluten: false, dairy: false },
  { id: 97, name: "Beterraba cozida", tag: "veg", kcal: 32, protein: 1.3, carbs: 7.2, fat: 0.1, fiber: 1.9, gluten: false, dairy: false },
  { id: 100, name: "Brócolis cozido", tag: "veg", kcal: 25, protein: 2.1, carbs: 4.4, fat: 0.5, fiber: 3.4, gluten: false, dairy: false },
  { id: 107, name: "Cebola", tag: "veg", kcal: 39, protein: 1.7, carbs: 8.9, fat: 0.1, fiber: 2.2, gluten: false, dairy: false },
  { id: 110, name: "Cenoura crua", tag: "veg", kcal: 34, protein: 1.3, carbs: 7.7, fat: 0.2, fiber: 3.2, gluten: false, dairy: false },
  { id: 112, name: "Chuchu cozido", tag: "veg", kcal: 19, protein: 0.4, carbs: 4.8, fat: 0, fiber: 1, gluten: false, dairy: false },
  { id: 115, name: "Couve crua", tag: "veg", kcal: 27, protein: 2.9, carbs: 4.3, fat: 0.5, fiber: 3.1, gluten: false, dairy: false },
  { id: 142, name: "Pepino", tag: "veg", kcal: 10, protein: 0.9, carbs: 2, fat: 0, fiber: 1.1, gluten: false, dairy: false },
  { id: 157, name: "Tomate", tag: "veg", kcal: 15, protein: 1.1, carbs: 3.1, fat: 0.2, fiber: 1.2, gluten: false, dairy: false },
];
export const foodTags = ["protein", "carb", "legume", "veg", "fruit", "dairy", "fat", "sweet", "nut"];
