// Tradução Almeida Revista e Corrigida (domínio público).
export const verses = [
  { text: "Este é o dia que fez o Senhor; regozijemo-nos, e alegremo-nos nele.", ref: "Salmos 118:24" },
  { text: "As misericórdias do Senhor são a causa de não sermos consumidos; porque as suas misericórdias não têm fim; renovam-se cada manhã. Grande é a tua fidelidade.", ref: "Lamentações 3:22-23" },
  { text: "Louvai ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre.", ref: "Salmos 118:1" },
  { text: "Posso todas as coisas em Cristo que me fortalece.", ref: "Filipenses 4:13" },
  { text: "Não estejais inquietos por coisa alguma; antes, as vossas petições sejam em tudo conhecidas diante de Deus, pela oração e súplicas, com ação de graças.", ref: "Filipenses 4:6" },
  { text: "Regozijai-vos sempre. Orai sem cessar. Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco.", ref: "1 Tessalonicenses 5:16-18" },
  { text: "O Senhor é o meu pastor; nada me faltará.", ref: "Salmos 23:1" },
  { text: "Pela tarde pode durar o choro, mas ao romper da manhã há alegria.", ref: "Salmos 30:5" },
  { text: "Mas os que esperam no Senhor renovarão as forças, subirão com asas como águias; correrão, e não se cansarão; caminharão, e não se fatigarão.", ref: "Isaías 40:31" },
  { text: "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.", ref: "Provérbios 3:5-6" },
  { text: "Não to mandei eu? Esforça-te, e tem bom ânimo; não temas, nem te espantes; porque o Senhor teu Deus é contigo, por onde quer que andares.", ref: "Josué 1:9" },
  { text: "Dai graças ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre.", ref: "Salmos 136:1" },
  { text: "E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus.", ref: "Romanos 8:28" },
  { text: "Não vos inquieteis, pois, pelo dia de amanhã, porque o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu mal.", ref: "Mateus 6:34" },
  { text: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.", ref: "Salmos 46:1" },
  { text: "Elevo os meus olhos para os montes; de onde vem o meu socorro? O meu socorro vem do Senhor, que fez o céu e a terra.", ref: "Salmos 121:1-2" },
  { text: "A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza.", ref: "2 Coríntios 12:9" },
  { text: "Provai, e vede que o Senhor é bom; bem-aventurado o homem que confia nele.", ref: "Salmos 34:8" },
  { text: "Ora, àquele que é poderoso para fazer tudo muito mais abundantemente além daquilo que pedimos ou pensamos, conforme o poder que em nós opera.", ref: "Efésios 3:20" },
  { text: "Porque eu bem sei os pensamentos que penso de vós, diz o Senhor; pensamentos de paz, e não de mal, para vos dar o fim que esperais.", ref: "Jeremias 29:11" },
  { text: "Tu me farás ver a vereda da vida; na tua presença há fartura de alegria; à tua mão direita há delícias perpetuamente.", ref: "Salmos 16:11" },
  { text: "Deleita-te também no Senhor, e ele te concederá os desejos do teu coração.", ref: "Salmos 37:4" },
  { text: "Faze-me ouvir a tua benignidade pela manhã, pois em ti confio.", ref: "Salmos 143:8" },
  { text: "E, quanto fizerdes por palavras ou por obras, fazei tudo em nome do Senhor Jesus, dando por ele graças a Deus Pai.", ref: "Colossenses 3:17" },
  { text: "Entrai pelas suas portas com ações de graças, e em seus átrios com louvor; louvai-o, e bendizei o seu nome. Porque o Senhor é bom, e eterna é a sua benignidade.", ref: "Salmos 100:4-5" },
  { text: "O Senhor te abençoe, e te guarde; o Senhor faça resplandecer o seu rosto sobre ti, e tenha misericórdia de ti; o Senhor sobre ti levante o seu rosto, e te dê a paz.", ref: "Números 6:24-26" },
  { text: "O Senhor é a minha luz e a minha salvação; a quem temerei? O Senhor é a força da minha vida; de quem me recearei?", ref: "Salmos 27:1" },
  { text: "Todavia eu me alegrarei no Senhor, exultarei no Deus da minha salvação.", ref: "Habacuque 3:18" },
  { text: "Toda a boa dádiva e todo o dom perfeito é do alto, descendo do Pai das luzes.", ref: "Tiago 1:17" },
  { text: "Bom é o Senhor para com todos, e as suas misericórdias são sobre todas as suas obras.", ref: "Salmos 145:9" },
  { text: "Eu vim para que tenham vida, e a tenham com abundância.", ref: "João 10:10" },
  { text: "Esforça-te, e tem bom ânimo; não temas, nem te espantes diante deles; porque o Senhor teu Deus é o que vai contigo; não te deixará, nem te desamparará.", ref: "Deuteronômio 31:6" },
  { text: "Alegrem-se todos os que confiam em ti; exultem eles para sempre, porquanto tu os defendes.", ref: "Salmos 5:11" },
  { text: "A tua benignidade é melhor do que a vida; os meus lábios te louvarão.", ref: "Salmos 63:3" },
  { text: "E a paz de Deus domine em vossos corações, para a qual também fostes chamados em um corpo; e sede agradecidos.", ref: "Colossenses 3:15" },
  { text: "Eu te louvarei, porque de um modo tão admirável, e tão maravilhoso fui feito; maravilhosas são as tuas obras.", ref: "Salmos 139:14" },
  { text: "O coração alegre serve de bom remédio, mas o espírito abatido seca os ossos.", ref: "Provérbios 17:22" },
  { text: "Farta-nos de manhã com a tua benignidade, para que nos regozijemos, e nos alegremos todos os nossos dias.", ref: "Salmos 90:14" },
  { text: "Por isso não desfalecemos; mas, ainda que o nosso homem exterior se corrompa, o interior, contudo, se renova de dia em dia.", ref: "2 Coríntios 4:16" },
  { text: "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.", ref: "Mateus 11:28" },
  { text: "E não nos cansemos de fazer bem, pois a seu tempo ceifaremos, se não houvermos desfalecido.", ref: "Gálatas 6:9" },
  { text: "O Senhor é a minha força e o meu escudo; nele confiou o meu coração, e fui socorrido; pelo que o meu coração salta de prazer.", ref: "Salmos 28:7" },
  { text: "Louvai ao Senhor, porque ele é bom, porque a sua benignidade dura para sempre.", ref: "1 Crônicas 16:34" },
  { text: "Bom é louvar ao Senhor, e cantar louvores ao teu nome, ó Altíssimo; anunciar de manhã a tua benignidade, e cada noite a tua fidelidade.", ref: "Salmos 92:1-2" },
  { text: "Dando sempre graças por tudo a nosso Deus e Pai, em nome de nosso Senhor Jesus Cristo.", ref: "Efésios 5:20" },
  { text: "Louvar-te-ei, Senhor, com todo o meu coração; contarei todas as tuas maravilhas.", ref: "Salmos 9:1" },
  { text: "Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios. Quem te farta a boca de bens, de sorte que a tua mocidade se renova como a da águia.", ref: "Salmos 103:2,5" },
  { text: "Mas eu esperarei continuamente, e cada vez mais te louvarei.", ref: "Salmos 71:14" },
  { text: "Que darei eu ao Senhor, por todos os benefícios que me tem feito?", ref: "Salmos 116:12" },
  { text: "Quanto ao homem a quem Deus deu riquezas e bens, e poder para desfrutar deles, e alegrar-se do seu trabalho, isso é dom de Deus.", ref: "Eclesiastes 5:19" },
];

export function verseOfDay(date = new Date()) {
  const days = Math.floor(date.getTime() / 86400000);
  const index = ((days % verses.length) + verses.length) % verses.length;
  return verses[index];
}
