// Bíblia Livre (blivre.com.br), licença CC BY 3.0 — tradução em português
// contemporâneo, livre para uso e adaptação com atribuição.
// 365 versículos, um por dia do ano (calculado pelo dia do calendário),
// selecionados e revisados manualmente por tema de gratidão e esperança.
export const verses = [
  { text: "O que era desde o princípio, o que ouvimos, o que vimos com os nossos olhos, o que temos contemplado, e nossas mãos tocaram, quanto à Palavra da vida,", ref: "1 João 1:1" },
  { text: "Jubilem e alegrem-se em ti todos os que te buscam; e aqueles que amam tua salvação digam continuamente: “Engrandecido seja Deus!”", ref: "Salmos 70:4" },
  { text: "Irmãos, o bom desejo do meu coração, e a oração que faço a Deus por Israel, é que sejam salvos.", ref: "Romanos 10:1" },
  { text: "Que o estranho te louve, e não tua própria boca; o estrangeiro, e não teus próprios lábios.", ref: "Provérbios 27:2" },
  { text: "Os que confiam no SENHOR são como o monte Sião, que não se abala, mas permanece para sempre.", ref: "Salmos 125:1" },
  { text: "Tu me guiarás com o teu conselho, e depois me receberás na glória.", ref: "Salmos 73:24" },
  { text: "O temor do homem arma ciladas; mas o que confia no senhor ficará em segurança.", ref: "Provérbios 29:25" },
  { text: "Os montes trarão paz ao povo, e as colinas, com justiça.", ref: "Salmos 72:3" },
  { text: "Portanto, também agora no presente tempo ficou um remanescente, escolhido pela graça.", ref: "Romanos 11:5" },
  { text: "Rogo-vos, pois, irmãos, pelas misericórdias de Deus, que apresenteis os vossos corpos como sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional.", ref: "Romanos 12:1" },
  { text: "Alguém entre vós está aflito? Ore. Alguém está contente? Cante louvores.", ref: "Tiago 5:13" },
  { text: "E a seu devido tempo a manifestou: a sua palavra, por meio da pregação, que me foi confiada segundo o mandamento de Deus nosso Salvador.", ref: "Tito 1:3" },
  { text: "Ouve, SENHOR, e tem misericórdia de mim; ó SENHOR, sê meu ajudador.", ref: "Salmos 30:10" },
  { text: "O justo dá atenção à vida de seus animais; mas até as misericórdias dos perversos são cruéis.", ref: "Provérbios 12:10" },
  { text: "A boca do homem são como águas profundas; e o manancial de sabedoria como um ribeiro transbordante.", ref: "Provérbios 18:4" },
  { text: "Rogo pois, que, quando eu estiver presente, não tenha de mostrar ousadia com a confiança de que penso que terei de me mostrar ousado para com alguns que nos consideram como se andássemos segundo a carne.", ref: "2 Coríntios 10:2" },
  { text: "Se é que já ouvistes da responsabilidade acerca da graça de Deus, que me foi dada para vós;", ref: "Efésios 3:2" },
  { text: "Como seu divino poder ele tem nos dado tudo o que pertence à vida e à devoção divina, por meio do conhecimento daquele que nos chamou à glória e virtude;", ref: "2 Pedro 1:3" },
  { text: "Pedindo-nos com muito entusiasmo que aceitássemos a graça e a comunhão deste serviço para os santos.", ref: "2 Coríntios 8:4" },
  { text: "O resgate da vida de cada um são suas riquezas; mas o pobre não ouve ameaças.", ref: "Provérbios 13:8" },
  { text: "Portanto, sede imitadores de Deus, como filhos amados;", ref: "Efésios 5:1" },
  { text: "É bom, porém, mostrar interesse para o bem sempre, e não somente quando estou presente convosco.", ref: "Gálatas 4:18" },
  { text: "A lembrança do justo será uma bênção; mas o nome dos perversos apodrecerá.", ref: "Provérbios 10:7" },
  { text: "E o que de mim ouviste entre muitas testemunhas, confia-o a pessoas fiéis, que sejam competentes para ensinar também a outros.", ref: "2 Timóteo 2:2" },
  { text: "Segui o amor, e desejai com zelo pelos dons espirituais; porém principalmente que profetizeis.", ref: "1 Coríntios 14:1" },
  { text: "Porque te acrescentarão extensão de dias, e anos de vida e paz.", ref: "Provérbios 3:2" },
  { text: "Ele restaura minha alma; guia-me pelas veredas de justiça por causa de seu nome.", ref: "Salmos 23:3" },
  { text: "Guarda minha alma, pois sou teu devoto; ó Deus, salva teu servo, que em ti confia.", ref: "Salmos 86:2" },
  { text: "O coração de seu marido confia nela, e ele não terá falta de bens.", ref: "Provérbios 31:11" },
  { text: "Mas quando a bondade e amor de Deus nosso Salvador para a humanidade apareceu,", ref: "Tito 3:4" },
  { text: "Dai graças ao SENHOR, porque ele é bom, porque seu leal amor é para sempre.", ref: "Salmos 136:1" },
  { text: "Bem vai ao homem que é misericordioso e empresta; ele conduz suas negócios com justiça.", ref: "Salmos 112:5" },
  { text: "E a outro fé pelo mesmo Espírito; e a outro dons de curas, pelo mesmo Espírito.", ref: "1 Coríntios 12:9" },
  { text: "Restaura-nos, Deus; faze resplandecer teu rosto, e seremos salvos.", ref: "Salmos 80:3" },
  { text: "Aquele que anda sinceramente, e pratica a justiça; e de seu coração fala a verdade;", ref: "Salmos 15:2" },
  { text: "Os que abandonam a lei louvam ao perverso; porém os que guardam a lei lutarão contra eles.", ref: "Provérbios 28:4" },
  { text: "Tal conhecimento é maravilhoso demais para mim, tão alto que não posso compreendê -lo.", ref: "Salmos 139:6" },
  { text: "E por fim, sede todos de uma mesma mentalidade, compassivos, tenhais amor pelos irmãos, e sede misericordiosos e benevolentes.", ref: "1 Pedro 3:8" },
  { text: "Digo a verdade em Cristo, não minto, e minha consciência dá testemunho comigo pelo Espírito Santo,", ref: "Romanos 9:1" },
  { text: "Eu te louvarei entre os povos, SENHOR, e cantarei louvores a ti entre as nações;", ref: "Salmos 108:3" },
  { text: "Pois a terra que absorve a chuva que com frequência vem sobre ela, e produz vegetação proveitosa para aqueles por quem é lavrada, recebe a bênção de Deus.", ref: "Hebreus 6:7" },
  { text: "Portanto, se há alguma consolação em Cristo, se há algum conforto de amor, se há alguma comunhão do Espírito, se há afetos e compaixões,", ref: "Filipenses 2:1" },
  { text: "Perseverai na oração, vigiando nela com gratidão.", ref: "Colossenses 4:2" },
  { text: "Nós sempre devemos dar graças a Deus por vós, irmãos, como é o correto, porque vossa fé cresce muito, e o amor de cada um de todos vós pelos outros é cada vez maior;", ref: "2 Tessalonicenses 1:3" },
  { text: "Quem faz misericórdia ao pobre empresta ao SENHOR; e ele lhe pagará sua recompensa.", ref: "Provérbios 19:17" },
  { text: "Convivei com sabedoria com os que estão de fora, aproveitando o tempo oportuno.", ref: "Colossenses 4:5" },
  { text: "E isto mesmo vos escrevi, para que quando vier, não tenha tristeza dos que deveriam me alegrar, confiando de vós todos, que minha alegria é a alegria de todos vós.", ref: "2 Coríntios 2:3" },
  { text: "E toda língua confesse que Jesus Cristo é o Senhor, para a glória de Deus Pai.", ref: "Filipenses 2:11" },
  { text: "Meu socorro vem do SENHOR, que fez o céu e a terra.", ref: "Salmos 121:2" },
  { text: "Em vez disso, devíeis dizer: Se o Senhor quiser, e vivermos, faremos isso ou aquilo.", ref: "Tiago 4:15" },
  { text: "E sejamos atenciosos uns para com os outros, a fim de incentivar o amor e as boas obras;", ref: "Hebreus 10:24" },
  { text: "Em esperança da vida eterna, a qual Deus, que não pode mentir, prometeu antes dos princípios dos tempos,", ref: "Tito 1:2" },
  { text: "A eles nem sequer por um momento cedemos a nos sujeitarmos, para que a verdade do Evangelho permanecesse em vós.", ref: "Gálatas 2:5" },
  { text: "Aleluia! Louvai o nome do SENHOR; louvai-o vós, servos do SENHOR,", ref: "Salmos 135:1" },
  { text: "Antes, vós não éreis povo, mas agora sois povo de Deus. Antes, não havíeis recebido misericórdia, mas agora recebestes misericórdia.", ref: "1 Pedro 2:10" },
  { text: "Amados, agora somos filhos de Deus, e ainda não está manifesto o que seremos. Porém sabemos que, quando ele se manifestar, seremos semelhantes a ele, pois o veremos como ele é.", ref: "1 João 3:2" },
  { text: "Eis que tu desejas a verdade no íntimo, e no secreto me fazes conhecer a sabedoria.", ref: "Salmos 51:6" },
  { text: "Portanto tu, meu filho, fortifica-te na graça que há em Cristo Jesus.", ref: "2 Timóteo 2:1" },
  { text: "A recompensa da humildade e do temor ao SENHOR são riquezas, honra, e vida.", ref: "Provérbios 22:4" },
  { text: "Ao qual seja a glória para todo o sempre, Amém!", ref: "Gálatas 1:5" },
  { text: "Também, irmãos, vos fazemos saber a graça de Deus dada às igrejas da Macedônia,", ref: "2 Coríntios 8:1" },
  { text: "Por isso, irmãos, somos devedores, não à carne, para vivermos segundo a carne;", ref: "Romanos 8:12" },
  { text: "Eu, porém, invocarei a Deus, e o SENHOR me salvará.", ref: "Salmos 55:16" },
  { text: "Bendito seja o Deus e Pai do nosso Senhor Jesus Cristo, que nos abençoou com todas as bênçãos espirituais nos lugares celestiais em Cristo;", ref: "Efésios 1:3" },
  { text: "Buscai a paz com todos, e a santificação, sem a qual ninguém verá o Senhor.", ref: "Hebreus 12:14" },
  { text: "E os estimai muito com amor, por causa do trabalho deles. Tende paz entre vós.", ref: "1 Tessalonicenses 5:13" },
  { text: "(pois a vida já foi manifesta, e nós a vimos, demos testemunho, e vos anunciamos a vida eterna, que estava com o Pai, e a nós foi manifesta)", ref: "1 João 1:2" },
  { text: "Tu o fizeste um pouco menor que os anjos, de glória e de honra o coroaste, e o estabeleceste sobre as obras das tuas mãos;", ref: "Hebreus 2:7" },
  { text: "Porque assim como os sofrimentos de Cristo são abundantes em nós, assim também por Cristo é abundante nossa consolação.", ref: "2 Coríntios 1:5" },
  { text: "Para conhecer a sabedoria e a instrução; para entender as palavras da prudência;", ref: "Provérbios 1:2" },
  { text: "E confiamos no Senhor quanto a vós, de que vós estais fazendo e continuareis a fazer o que vos mandamos.", ref: "2 Tessalonicenses 3:4" },
  { text: "Ele julgará os aflitos do povo, salvará os filhos do necessitado, e quebrantará o opressor.", ref: "Salmos 72:4" },
  { text: "Mas o que profetiza, fala aos seres humanos para edificação, convencimento, e consolação.", ref: "1 Coríntios 14:3" },
  { text: "E não vos conformeis com a presente era; mas transformai-vos pela renovação da vossa mentalidade, para que experimenteis qual seja a boa, agradável, e perfeita vontade de Deus.", ref: "Romanos 12:2" },
  { text: "Porém tu, SENHOR, és escudo para mim; minha glória, e o que levanta minha cabeça.", ref: "Salmos 3:3" },
  { text: "Louvarei ao SENHOR enquanto eu viver; cantarei louvores ao meu Deus enquanto eu existir.", ref: "Salmos 146:2" },
  { text: "Abençoarei o seu mantimento abundantemente; saciarei de pão os seus necessitados.", ref: "Salmos 132:15" },
  { text: "Grande é o SENHOR, e muito louvável, na cidade de nosso Deus, em seu santo monte.", ref: "Salmos 48:1" },
  { text: "Meu coração está preparado, ó Deus; cantarei; entoarei louvores até com a minha alma.", ref: "Salmos 108:1" },
  { text: "Pois tu, SENHOR, és meu refúgio. Fizeste do Altíssimo tua habitação.", ref: "Salmos 91:9" },
  { text: "Sempre agradeço ao meu Deus por causa de vós, pela graça de Deus, que é dada a vós em Cristo Jesus.", ref: "1 Coríntios 1:4" },
  { text: "Mas, se por causa do que comes o teu irmão se entristece, tu já não estás andando segundo o amor. Não destruas por tua comida aquele por quem Cristo morreu.", ref: "Romanos 14:15" },
  { text: "Porque minha boca declarará a verdade; e meus lábios abominam a maldade.", ref: "Provérbios 8:7" },
  { text: "Vida eterna aos que procuram glória, honra, e imortalidade, fazendo o bem com perseverança;", ref: "Romanos 2:7" },
  { text: "Pois de fato nós, os que estamos neste tabernáculo, gememos pressionados, não porque queremos ser despidos, mas revestidos; para que a mortalidade seja devorada pela vida.", ref: "2 Coríntios 5:4" },
  { text: "Por isso eu te exorto, antes de tudo, que se façam pedidos, orações, intercessões e atos de gratidão por todas as pessoas;", ref: "1 Timóteo 2:1" },
  { text: "Pois eu disse: A leal bondade está edificada para sempre; estabeleces tua fidelidade nos céus,", ref: "Salmos 89:2" },
  { text: "Segundo a graça de Deus que me foi dada, eu, como sábio construtor, pus o fundamento; e outro edifica sobre ele; mas cada um veja como edifica sobre ele.", ref: "1 Coríntios 3:10" },
  { text: "O SENHOR abomina pesos falsificados; e balanças enganosas não são boas.", ref: "Provérbios 20:23" },
  { text: "SENHOR, tu fizeste subir minha alma do Xeol; conservaste-me em vida, para que eu não descesse à cova.", ref: "Salmos 30:3" },
  { text: "Eis que, como os olhos dos servos estão atentos à mão de seus senhores, e os olhos da serva à mão de sua senhora, assim também nossos olhos estão atentos ao SENHOR nosso Deus, até que ele tenha misericórdia de nós.", ref: "Salmos 123:2" },
  { text: "Como frio de neve no tempo da colheita, assim é o mensageiro fiel para aqueles que o enviam; porque ele refresca a alma de seus senhores.", ref: "Provérbios 25:13" },
  { text: "É glória de Deus encobrir alguma coisa; mas a glória dos Reis é investigá-la.", ref: "Provérbios 25:2" },
  { text: "Por isso vos peço que confirmeis o amor para com ele.", ref: "2 Coríntios 2:8" },
  { text: "Louvarei ao SENHOR com todo o meu coração; contarei todas as tuas maravilhas.", ref: "Salmos 9:1" },
  { text: "Ouve, SENHOR, minha voz, eu clamo; tem misericórdia de mim, e responde-me.", ref: "Salmos 27:7" },
  { text: "Confia tuas obras ao SENHOR, e teus pensamentos serão firmados.", ref: "Provérbios 16:3" },
  { text: "Não havendo bois, o celeiro fica vazio; mas pela força do boi há uma colheita abundante.", ref: "Provérbios 14:4" },
  { text: "Porque se eu faço de boa mente, tenho recompensa; mas se eu fizer de má vontade, a responsabilidade me é confiada.", ref: "1 Coríntios 9:17" },
  { text: "Quando caminhares, isto te guiará; quando deitares, isto te guardará; quando acordares, isto falará contigo.", ref: "Provérbios 6:22" },
  { text: "E não é bom a alma sem conhecimento; e quem tem pés apressados comete erros.", ref: "Provérbios 19:2" },
  { text: "O SENHOR reina; que a terra jubile; as muitas ilhas se alegrem.", ref: "Salmos 97:1" },
  { text: "Portanto, cada um de nós agrade ao próximo no que é bom para a edificação.", ref: "Romanos 15:2" },
  { text: "Adquire sabedoria, adquire entendimento; e não te esqueças nem te desvies das palavras de minha boca.", ref: "Provérbios 4:5" },
  { text: "Quem toma cuidado com sua boca preserva sua alma; mas aquele que abre muito seus lábios será arruinado.", ref: "Provérbios 13:3" },
  { text: "Pois eu vos dou boa doutrina; não deixeis a minha lei.", ref: "Provérbios 4:2" },
  { text: "O SENHOR é grande e muito digno de louvor; sua grandeza é incompreensível.", ref: "Salmos 145:3" },
  { text: "Porque por mim teus dias serão multiplicados; e anos de vida a ti serão aumentados.", ref: "Provérbios 9:11" },
  { text: "Porém os mansos herdarão a terra, e se deleitarão com abundância de paz.", ref: "Salmos 37:11" },
  { text: "Eis que considerarmos benditos os que suportam o sofrimento. Ouvistes da paciência de Jó, e vistes o resultado da parte do Senhor; porque o Senhor é muito misericordioso, e cheio de compaixão.", ref: "Tiago 5:11" },
  { text: "Porque a sabedoria é melhor do que rubis; e todas as coisas desejáveis nem sequer podem ser comparadas a ela.", ref: "Provérbios 8:11" },
  { text: "Em ti me alegrarei e jubilarei; cantarei louvores a teu nome, ó Altíssimo.", ref: "Salmos 9:2" },
  { text: "Que Israel jubile no seu Criador, os filhos de Sião se alegrem no seu Rei.", ref: "Salmos 149:2" },
  { text: "Pois toda criatura de Deus é boa, e não há nada a rejeitar, se for recebida com gratidão.", ref: "1 Timóteo 4:4" },
  { text: "E pôs em minha boca uma canção nova, um louvor ao nosso Deus; muitos verão isso, e temerão, e confiarão no SENHOR.", ref: "Salmos 40:3" },
  { text: "Porque sabemos que, se nossa casa terrestre deste tabernáculo se desfizer, temos um edifício de Deus, uma casa não feita por mãos, mas eterna, nos céus.", ref: "2 Coríntios 5:1" },
  { text: "Pois Cristo não entrou num santuário feito por mãos, mera figura do verdadeiro; mas sim, no próprio Céu, para agora comparecer por nós diante da face de Deus.", ref: "Hebreus 9:24" },
  { text: "Aclamai ao SENHOR a glória de seu nome; adorai ao SENHOR na beleza da santidade.", ref: "Salmos 29:2" },
  { text: "Ora, se já morremos com Cristo, cremos que também com ele viveremos.", ref: "Romanos 6:8" },
  { text: "Pois este é o amor de Deus: que guardemos os seus mandamentos. E os seus mandamentos não são pesados.", ref: "1 João 5:3" },
  { text: "Alegrai-vos no SENHOR, e jubilai vós, os justos, e cantai alegremente todos vós que sois corretos de coração.", ref: "Salmos 32:11" },
  { text: "Louvai-o, sol e lua; louvai-o, todas as estrelas luminosas.", ref: "Salmos 148:3" },
  { text: "Para declarar com voz de louvores, e contar todas as tuas maravilhas.", ref: "Salmos 26:7" },
  { text: "Porque tu és minha rocha e minha fortaleza; e, por causa de teu nome, guia-me e me conduz.", ref: "Salmos 31:3" },
  { text: "Meu interior saltará de alegria quando teus lábios falarem coisas corretas.", ref: "Provérbios 23:16" },
  { text: "Não ponhais vossa confiança em príncipes; em filhos dos homens, que não podem salvar.", ref: "Salmos 146:3" },
  { text: "Por causa da força dele, eu te aguardarei; porque Deus é meu alto refúgio.", ref: "Salmos 59:9" },
  { text: "Certamente Deus é bom para Israel, para os puros de coração.", ref: "Salmos 73:1" },
  { text: "No restante, meus irmãos, alegrai-vos no Senhor. Não me é incômodo escrever as mesmas coisas, e isso é para a vossa segurança.", ref: "Filipenses 3:1" },
  { text: "Vestirei de salvação os seus sacerdotes; e seus santos jubilarão grandemente.", ref: "Salmos 132:16" },
  { text: "Minha leal bondade e minha fortaleza; meu alto refúgio, e meu libertador; meu escudo, em quem confio; e aquele que submete o meu povo a mim.", ref: "Salmos 144:2" },
  { text: "Este receberá a bênção do SENHOR, e a justiça do Deus de sua salvação.", ref: "Salmos 24:5" },
  { text: "Aleluia! Darei graças ao SENHOR de todo o coração, no conselho dos justos, e na assembleia.", ref: "Salmos 111:1" },
  { text: "Portanto ninguém o despreze; mas enviai-o em paz, para que ele venha a mim; porque eu o espero com os irmãos.", ref: "1 Coríntios 16:11" },
  { text: "Meus irmãos, tende toda alegria quando vos encontrardes em várias provações,", ref: "Tiago 1:2" },
  { text: "Louvai ao SENHOR, todas as nações; celebrai a ele, todos os povos.", ref: "Salmos 117:1" },
  { text: "Mostra-nos tua leal bondade, SENHOR, e concede-nos tua salvação.", ref: "Salmos 85:7" },
  { text: "E se faço o que não quero, consinto que a Lei é boa;", ref: "Romanos 7:16" },
  { text: "Eu me prostrarei ao teu santo templo, e louvarei teu nome por tua leal bondade e por tua verdade; porque engrandeceste tua palavra acima de toda a tua fama.", ref: "Salmos 138:2" },
  { text: "Em Deus louvarei sua palavra; no SENHOR louvarei sua palavra.", ref: "Salmos 56:10" },
  { text: "Que sacia teu desejo de boas coisas, de modo que tua juventude se renova como a águia.", ref: "Salmos 103:5" },
  { text: "Ah, que de Sião venha a salvação de Israel! Quando Deus restaurar o destino do seu povo, Jacó jubilará, e Israel se alegrará.", ref: "Salmos 53:6" },
  { text: "Quem segue a justiça e a bondade achará vida, justiça e honra.", ref: "Provérbios 21:21" },
  { text: "Alegria para o justo é fazer justiça; mas isso é pavor para os que praticam maldade.", ref: "Provérbios 21:15" },
  { text: "O SENHOR é minha rocha, minha fortaleza, e meu libertador; meu Deus, meu rochedo, em quem confio; meu escudo, a força de minha salvação, meu alto refúgio.", ref: "Salmos 18:2" },
  { text: "Com misericórdia e fidelidade a perversidade é reconciliada; e com o temor ao SENHOR se desvia do mal.", ref: "Provérbios 16:6" },
  { text: "O louvor espera por ti, ó Deus, em Sião; e a ti se pagará o voto.", ref: "Salmos 65:1" },
  { text: "Além disso, exige-se dos guardiões que cada um seja fiel.", ref: "1 Coríntios 4:2" },
  { text: "O perverso tem muitas dores, mas aquele que confia no SENHOR, a leal bondade o rodeará.", ref: "Salmos 32:10" },
  { text: "Pois, por meio do Espírito, pela fé, aguardamos a esperança da justiça;", ref: "Gálatas 5:5" },
  { text: "Contai sua glória por entre as nações, suas maravilhas por entre todos os povos.", ref: "Salmos 96:3" },
  { text: "Mas fiel é o Senhor, que vos fortalecerá e vos guardará do maligno.", ref: "2 Tessalonicenses 3:3" },
  { text: "Entrai por suas portas com ações de graças, por seus pátios com cântico de louvor; dai graças a ele, e bendizei o seu nome.", ref: "Salmos 100:4" },
  { text: "Ó SENHOR, foste favorável à tua terra; restauraste o destino de Jacó.", ref: "Salmos 85:1" },
  { text: "O caminho de Deus é perfeito; a palavra do SENHOR é comprovada; ele é escudo para todos os que nele confiam.", ref: "Salmos 18:30" },
  { text: "Batei palmas vós, todos os povos; jubilai a Deus com voz de alegria.", ref: "Salmos 47:1" },
  { text: "Vede quão grande amor o Pai tem nos dado, que fôssemos chamados filhos de Deus. Por isso o mundo não nos conhece, pois não conhece a ele.", ref: "1 João 3:1" },
  { text: "Pois tu lhe providencias bênçãos de bondade; pões em sua cabeça uma coroa de ouro puro.", ref: "Salmos 21:3" },
  { text: "Meu coração transborda de boas palavras; digo o que fiz a respeito do Rei; minha língua é a pena de um habilidoso escritor.", ref: "Salmos 45:1" },
  { text: "Mas Deus, que é rico em misericórdia, pelo seu muito amor com que nos amou,", ref: "Efésios 2:4" },
  { text: "Que Deus tenha misericórdia de nós e nos abençoe; que ele faça brilhar seu rosto sobre nós. (Selá)", ref: "Salmos 67:1" },
  { text: "Pois já morrestes, e a vossa vida está escondida com Cristo em Deus.", ref: "Colossenses 3:3" },
  { text: "Louvem o teu grande e temível nome; ele é santo.", ref: "Salmos 99:3" },
  { text: "Pois para isto Cristo também morreu, ressuscitou, e voltou a viver, para ser Senhor tanto dos mortos como dos vivos.", ref: "Romanos 14:9" },
  { text: "Servindo de boa vontade como ao Senhor, e não aos pessoas.", ref: "Efésios 6:7" },
  { text: "Nem duvidou da promessa de Deus; pelo contrário, fortaleceu-se na fé, dando glória a Deus;", ref: "Romanos 4:20" },
  { text: "Para a qual ele vos chamou por meio do nosso Evangelho, para a obtenção da glória de nosso Senhor Jesus Cristo.", ref: "2 Tessalonicenses 2:14" },
  { text: "Ele é fiel àquele que o constituiu, assim como Moisés também foi em toda a casa de Deus.", ref: "Hebreus 3:2" },
  { text: "Ó SENHOR, ouve minha oração; inclina os ouvidos às minhas súplicas; responde-me conforme tua fidelidade e tua justiça.", ref: "Salmos 143:1" },
  { text: "Minha boca falará sabedoria, e o pensamento de meu coração será de entendimento.", ref: "Salmos 49:3" },
  { text: "Porque todos pecaram, e estão destituídos da glória de Deus;", ref: "Romanos 3:23" },
  { text: "Cantai com alegria a Deus, nossa força; jubilai ao Deus de Jacó.", ref: "Salmos 81:1" },
  { text: "Agradecemos ao Deus e Pai do nosso Senhor Jesus Cristo, sempre orando por vós;", ref: "Colossenses 1:3" },
  { text: "Alegra-nos conforme os dias em que tu nos afligiste, e os anos em que experimentamos a adversidade.", ref: "Salmos 90:15" },
  { text: "Graças te damos, ó Deus; graças te damos, pois perto está o teu nome; anunciadas são tuas maravilhas.", ref: "Salmos 75:1" },
  { text: "Para anunciar tua bondade de manhã, e tua fidelidade durante as noites.", ref: "Salmos 92:2" },
  { text: "Na multidão de minhas preocupações dentro de mim, tuas consolações alegram minha alma.", ref: "Salmos 94:19" },
  { text: "Louvai ao SENHOR, porque o SENHOR é bom; cantai louvores ao seu nome, porque é agradável;", ref: "Salmos 135:3" },
  { text: "Mas pela graça de Deus sou o que sou; e sua graça concedida a mim não foi vã; ao invés disso trabalhei muito mais que todos eles; porém não eu, mas a graça de Deus que está comigo.", ref: "1 Coríntios 15:10" },
  { text: "Ó minha alma, por que estás abatida, e te inquietas em mim? Espera em Deus; pois ainda o louvarei pelas salvações de sua presença.", ref: "Salmos 42:5" },
  { text: "Jesus Cristo é o mesmo ontem, hoje, e eternamente.", ref: "Hebreus 13:8" },
  { text: "Os perversos fogem mesmo quando não há quem os persiga, mas os justos são confiantes como um leão.", ref: "Provérbios 28:1" },
  { text: "Grandes coisas o SENHOR fez a nós; por isso estamos alegres.", ref: "Salmos 126:3" },
  { text: "Bendito és tu, SENHOR; ensina-me teus estatutos.", ref: "Salmos 119:12" },
  { text: "Aquele que não tem entendimento despreza a seu próximo; mas o homem bom entendedor se mantêm calado.", ref: "Provérbios 11:12" },
  { text: "SENHOR, o rei se alegra em tua força, e grandemente jubila em tua salvação.", ref: "Salmos 21:1" },
  { text: "Por ele recebemos graça e apostolado, para a obediência da fé entre todas as nações, por causa do seu nome.", ref: "Romanos 1:5" },
  { text: "E andai em amor, como também Cristo nos amou, e se entregou por nós como oferta e sacrifício de cheiro suave a Deus.", ref: "Efésios 5:2" },
  { text: "Deus também deu testemunho com eles, por meio de sinais, milagres, várias maravilhas, e distribuições do Espírito Santo, segundo a sua vontade.", ref: "Hebreus 2:4" },
  { text: "É preferível ter um bom nome do que muitas riquezas; e ser favorecido é melhor que a prata e o o ouro.", ref: "Provérbios 22:1" },
  { text: "E se o Espírito daquele que dos mortos ressuscitou Jesus habita em vós, aquele que dos mortos ressuscitou Cristo também dará vida aos vossos corpos mortais por meio do seu Espírito, que habita em vós.", ref: "Romanos 8:11" },
  { text: "A Lei não provém da fé; porém: Quem fizer estas coisas por elas viverá.", ref: "Gálatas 3:12" },
  { text: "Dai graças ao SENHOR, invocai o seu nome; anunciai suas obras entre os povos.", ref: "Salmos 105:1" },
  { text: "Mantenhamos firme a esperança que declararmos ter, sem abalo algum, pois aquele que prometeu é fiel;", ref: "Hebreus 10:23" },
  { text: "Peço também de ti, verdadeiro companheiro, que ajude a essas que lutaram no Evangelho comigo, como também com Clemente, e com os demais cooperadores, cujos nomes estão no livro da vida.", ref: "Filipenses 4:3" },
  { text: "Os céus declaram a glória de Deus; e o firmamento anuncia a obra de suas mãos.", ref: "Salmos 19:1" },
  { text: "O coração alegre anima o rosto, mas pela dor do coração o espírito se abate.", ref: "Provérbios 15:13" },
  { text: "Assim cantarei louvores ao teu nome para sempre, para eu cumprir diariamente os meus votos.", ref: "Salmos 61:8" },
  { text: "Por meio dele também temos acesso pela fé a esta graça, na qual estamos firmes, e nos alegramos na esperança da glória de Deus.", ref: "Romanos 5:2" },
  { text: "Vede como é bom e agradável que os irmãos vivam em união!", ref: "Salmos 133:1" },
  { text: "Aleluia! Louvai, servos do SENHOR, louvai o nome do SENHOR.", ref: "Salmos 113:1" },
  { text: "Eu clamo a ti, SENHOR; digo: “Tu és meu refúgio, minha porção na terra dos viventes”.", ref: "Salmos 142:5" },
  { text: "A ninguém devais coisa alguma, a não ser o amor uns aos outros, pois quem ama o outro tem cumprido a Lei.", ref: "Romanos 13:8" },
  { text: "O SENHOR é minha porção da herança e meu cálice; tu sustentas minha sorte.", ref: "Salmos 16:5" },
  { text: "Meu filho, presta atenção à minha sabedoria, inclina teus ouvidos ao meu entendimento.", ref: "Provérbios 5:1" },
  { text: "Mas aquele que é instruído na palavra compartilhe todas as boas coisas com aquele que o instrui.", ref: "Gálatas 6:6" },
  { text: "Mas nós, que somos do dia, sejamos sóbrios, e nos vistamos da couraça da fé e do amor, e do capacete da esperança da salvação.", ref: "1 Tessalonicenses 5:8" },
  { text: "Portanto, se comerdes, ou se beberdes, ou se fizerdes qualquer coisa, fazei tudo para a glória de Deus.", ref: "1 Coríntios 10:31" },
  { text: "O SENHOR é compassivo e justo; nosso Deus é misericordioso.", ref: "Salmos 116:5" },
  { text: "Agora sei que o SENHOR salva seu ungido; ele lhe responderá desde seu santo céu, com a força salvadora de sua mão direita.", ref: "Salmos 20:6" },
  { text: "Melhor é a repreensão clara do que o amor escondido.", ref: "Provérbios 27:5" },
  { text: "Quem oferece sacrifício de gratidão me glorifica, e ao que prepara bem seu caminho, eu mostrarei a salvação de Deus.", ref: "Salmos 50:23" },
  { text: "Oh, que a salvação para Israel venha de Sião! Quando o SENHOR restaurar o destino de seu povo, Jacó jubilará, Israel se alegrará.", ref: "Salmos 14:7" },
  { text: "Os sinais do meu apostolado foram efetuados entre vós em toda paciência, em sinais, milagres e maravilhas.", ref: "2 Coríntios 12:12" },
  { text: "Tem misericórdia de mim, ó SENHOR, pois clamo a ti o dia todo.", ref: "Salmos 86:3" },
  { text: "Mas Deus, que consola aos abatidos, nos consolou com a vinda de Tito.", ref: "2 Coríntios 7:6" },
  { text: "Porque nada podemos fazer contra a verdade, mas sim pela verdade.", ref: "2 Coríntios 13:8" },
  { text: "Experimentai e vede que o SENHOR é bom; bem-aventurado é o homem que nele confia.", ref: "Salmos 34:8" },
  { text: "O homem sábio é poderoso; e o homem que tem conhecimento aumenta sua força;", ref: "Provérbios 24:5" },
  { text: "Pelo bênção dos sinceros a cidade se exalta; mas pela boca dos perversos ela se destrói.", ref: "Provérbios 11:11" },
  { text: "Então as nações temerão o nome do SENHOR; e todos os reis da terra, a tua glória.", ref: "Salmos 102:15" },
  { text: "Belo lugar elevado, e alegria de toda a terra, é o monte Sião, sobre os lados do norte, a cidade do grande Rei.", ref: "Salmos 48:2" },
  { text: "Ó SENHOR, tua leal bondade está nos céus, e tua fidelidade vai até as nuvens.", ref: "Salmos 36:5" },
  { text: "Mas ele me disse: “Minha graça te basta, porque meu poder se aperfeiçoa na fraqueza”. Por isso, com muito prazer, eu me orgulharei nas minhas fraquezas, para que o poder de Cristo habite em mim.", ref: "2 Coríntios 12:9" },
  { text: "Porque o SENHOR dá sabedoria; de sua boca vem o conhecimento e o entendimento.", ref: "Provérbios 2:6" },
  { text: "Pois quem semear para a sua carne, da carne colherá degradação; mas quem semear para o Espírito, do Espírito colherá a vida eterna.", ref: "Gálatas 6:8" },
  { text: "Portanto, os que são da fé são abençoados com o crente Abraão.", ref: "Gálatas 3:9" },
  { text: "E este é o testemunho: que Deus nos deu a vida eterna; e essa vida está no seu Filho.", ref: "1 João 5:11" },
  { text: "Portanto, meus amados e queridos irmãos, minha alegria e coroa, permanecei assim, firmes no Senhor, amados.", ref: "Filipenses 4:1" },
  { text: "Aleluia! Pois é bom cantar louvores ao nosso Deus, porque é agradável; e apropriado é o louvor.", ref: "Salmos 147:1" },
  { text: "Que foi constituído, não conforme a Lei de um mandamento carnal, mas sim, conforme o poder de uma vida indestrutível.", ref: "Hebreus 7:16" },
  { text: "Assim eu te contemplava no santuário, para ver teu poder e tua glória.", ref: "Salmos 63:2" },
  { text: "Se, de fato, já experimentastes que o Senhor é bom.", ref: "1 Pedro 2:3" },
  { text: "Eis que assim será abençoado o homem que teme o SENHOR.", ref: "Salmos 128:4" },
  { text: "Livra-me em tua justiça, e resgata-me; inclina teus ouvidos a mim, e salva-me.", ref: "Salmos 71:2" },
  { text: "Que são israelitas, e a quem pertencem a adoção como filhos, a glória, os pactos, a Lei, o culto, e as promessas;", ref: "Romanos 9:4" },
  { text: "Cada um sirva aos outros segundo o dom que recebeu, como bons administradores da variada graça de Deus.", ref: "1 Pedro 4:10" },
  { text: "Louvo ao SENHOR, que me aconselha; até de noite meu coração me ensina.", ref: "Salmos 16:7" },
  { text: "Mas os justos se alegram, e jubilam na presença de Deus, e saltam de alegria.", ref: "Salmos 68:3" },
  { text: "Vinde, cantemos ao SENHOR; jubilemos à rocha da nossa salvação.", ref: "Salmos 95:1" },
  { text: "Pois, como os céus estão elevados acima da terra, assim é grande sua leal bondade para com os que o temem.", ref: "Salmos 103:11" },
  { text: "Pois o fizeste um pouco menor que os seres divinos; e o coroaste com glória e honra.", ref: "Salmos 8:5" },
  { text: "Há bênçãos sobre a cabeça dos justos; mas a violência cobre a boca dos perversos.", ref: "Provérbios 10:6" },
  { text: "Portanto façamos festa, não no velho fermento, nem no fermento do mal e da perversão, mas em pães não levedados de sinceridade e de verdade.", ref: "1 Coríntios 5:8" },
  { text: "Porque sua leal bondade é grande para conosco, e a fidelidade do SENHOR dura para sempre. Aleluia!", ref: "Salmos 117:2" },
  { text: "O SENHOR te abençoe desde Sião, e que tu vejas a prosperidade de Jerusalém todos os dias de tua vida;", ref: "Salmos 128:5" },
  { text: "Guia-me em tua verdade, e ensina-me; pois tu és o Deus de minha salvação; por ti espero todo o dia.", ref: "Salmos 25:5" },
  { text: "Exalta-te sobre os céus, ó Deus; seja tua glória sobre toda a terra.", ref: "Salmos 57:5" },
  { text: "Aquele que fala a verdade conta a justiça; porém a testemunha falsa conta o engano.", ref: "Provérbios 12:17" },
  { text: "Além disto eu mesmo, Paulo, pela mansidão e bondade de Cristo, rogo-vos, eu, que em verdade sou humilde entre vós quando presente, porém ousado para convosco quando ausente;", ref: "2 Coríntios 10:1" },
  { text: "Para fazeres teus ouvidos darem atenção à sabedoria, e inclinares teu coração à inteligência;", ref: "Provérbios 2:2" },
  { text: "A fim de que pusessem sua esperança em Deus, e não se esquecessem dos feitos de Deus, mas guardassem os mandamentos dele;", ref: "Salmos 78:7" },
  { text: "Tem misericórdia de mim, SENHOR, porque estou fraco; cura-me, SENHOR, porque meus ossos estão perturbados.", ref: "Salmos 6:2" },
  { text: "Alegrei-me quando me disseram: “Vamos à casa do SENHOR”.", ref: "Salmos 122:1" },
  { text: "Salva-me, Deus, por teu nome; e faze-me justiça por teu poder.", ref: "Salmos 54:1" },
  { text: "Mas eu o anunciarei para sempre; cantarei louvores ao Deus de Jacó.", ref: "Salmos 75:9" },
  { text: "Porque o mandamento é uma lâmpada, e a lei é luz; e as repreensões para correção são o caminho da vida;", ref: "Provérbios 6:23" },
  { text: "Só ele é minha rocha, minha salvação, e meu alto refúgio; não serei muito abalado.", ref: "Salmos 62:2" },
  { text: "Aleluia! Louvai ao SENHOR desde os céus; louvai-o nas alturas.", ref: "Salmos 148:1" },
  { text: "E nós, como trabalhadores conjuntamente com ele, rogamos que não tenhais recebido a graça de Deus em vão.", ref: "2 Coríntios 6:1" },
  { text: "Levanta-te para nos socorrer; e resgata-nos por causa de tua leal bondade.", ref: "Salmos 44:26" },
  { text: "O zombador busca sabedoria, mas não acha nenhuma; mas o conhecimento é fácil para o prudente.", ref: "Provérbios 14:6" },
  { text: "Sempre damos graças a Deus por todos vós, fazendo menção de vós em nossas orações.", ref: "1 Tessalonicenses 1:2" },
  { text: "Louvai-o por seus atos poderosos; louvai-o conforme a imensidão de sua grandeza.", ref: "Salmos 150:2" },
  { text: "SENHOR, meu Deus, em ti confio; salva-me de todos os meus perseguidores, e livra-me.", ref: "Salmos 7:1" },
  { text: "E são justificados gratuitamente pela sua graça, por meio da redenção que há em Cristo Jesus.", ref: "Romanos 3:24" },
  { text: "Servi vós ao SENHOR com alegria; vinde perante sua presença com cântico.", ref: "Salmos 100:2" },
  { text: "Dai graças ao Deus dos deuses, porque seu leal amor é para sempre.", ref: "Salmos 136:2" },
  { text: "O justo se alegará no SENHOR, e confiará nele; e todos os corretos de coração lhe darão glória.", ref: "Salmos 64:10" },
  { text: "Bom é louvar ao SENHOR, e cantar louvores ao teu nome, ó Altíssimo;", ref: "Salmos 92:1" },
  { text: "Até ali tua mão me guiará, e tua mão direita me sustentará.", ref: "Salmos 139:10" },
  { text: "Ora, sem contradição alguma, o menor é abençoado pelo maior.", ref: "Hebreus 7:7" },
  { text: "Toda palavra de Deus é pura; é escudo para os que nele confiam.", ref: "Provérbios 30:5" },
  { text: "Faze-me ouvir tua leal bondade pela manhã, pois em ti confio; faze-me saber o caminho que devo seguir, porque a ti elevo minha alma.", ref: "Salmos 143:8" },
  { text: "Porque eu sei a prontidão de vosso ânimo, do qual eu me orgulho de vós para os Macedônios, que Acaia já está pronta desde o ano passado; e o zelo que começou de vós tem estimulado a muitos.", ref: "2 Coríntios 9:2" },
  { text: "Nele estão ocultos todos os tesouros da sabedoria e do conhecimento.", ref: "Colossenses 2:3" },
  { text: "Então irei ao altar de Deus, ao Deus que é minha grande alegria, e com harpa te louvarei, ó Deus, meu Deus.", ref: "Salmos 43:4" },
  { text: "Eu, porém, faço minha oração a ti, ó SENHOR, num tempo aceitável; Ó Deus, responde-me pela grandeza de tua leal bondade, pela fidelidade de tua salvação.", ref: "Salmos 69:13" },
  { text: "A coroa dos idosos são os filhos de seus filhos; e a glória dos filhos são seus pais.", ref: "Provérbios 17:6" },
  { text: "Pois os que possuem autoridade não causam temor às boas obras, mas sim, às más. Queres tu não ter medo de autoridade? Faz o bem, e dela receberás elogio,", ref: "Romanos 13:3" },
  { text: "Nenhuma tentação vos veio, que não fosse humana; porém Deus é fiel; que não vos deixará tentar mais do que o que podeis, antes com a tentação também dará a saída, para que a possais suportar.", ref: "1 Coríntios 10:13" },
  { text: "SENHOR, meu coração não se exalta, nem meus olhos são elevados; não me ocupo com coisas grandiosas, nem com coisas maravilhosas demais para mim.", ref: "Salmos 131:1" },
  { text: "Aleluia! Cantai ao SENHOR um cântico novo; um louvor a ele na assembleia dos santos.", ref: "Salmos 149:1" },
  { text: "Quando eu digo: “Meu pé está deslizando”; tua leal bondade, ó SENHOR, me sustenta.", ref: "Salmos 94:18" },
  { text: "Meu filho, se teu coração for sábio, meu coração se alegrará, e eu também.", ref: "Provérbios 23:15" },
  { text: "Quando Cristo, que é a nossa vida, se manifestar, então também vós vos manifestareis com ele em glória.", ref: "Colossenses 3:4" },
  { text: "SENHOR, guia-me em tua justiça, por causa de meus adversários; prepara diante de mim teu caminho.", ref: "Salmos 5:8" },
  { text: "Por isso, já que temos este ministério, segundo a misericórdia que nos foi feita, não desanimamos.", ref: "2 Coríntios 4:1" },
  { text: "Eu fui feito servidor desse evangelho conforme o dom da graça de Deus, que me foi dada segundo a operação do seu poder.", ref: "Efésios 3:7" },
  { text: "Uma língua sã é árvore de vida; mas a perversidade nela é faz o espírito em pedaços.", ref: "Provérbios 15:4" },
  { text: "Se informares essas coisas aos irmãos, serás um bom servidor de Jesus Cristo, alimentado com as palavras da fé e de boa doutrina que tens seguido.", ref: "1 Timóteo 4:6" },
  { text: "Cantai ao SENHOR um cântico novo, porque ele fez maravilhas; sua mão direita e seu santo braço lhe alcançaram a salvação.", ref: "Salmos 98:1" },
  { text: "Seja bendito o nome do SENHOR, desde agora e para sempre.", ref: "Salmos 113:2" },
  { text: "Porque ele inclinou a mim seus ouvidos; por isso o invocarei enquanto eu viver.", ref: "Salmos 116:2" },
  { text: "Para que guardes o bom-senso; e teus lábios conservem o conhecimento.", ref: "Provérbios 5:2" },
  { text: "Procurai guardar a unidade do Espírito pelo vínculo da paz.", ref: "Efésios 4:3" },
  { text: "Que a bondade e a fidelidade não te desamparem; amarra-as junto ao teu pescoço; escreve-as na tábua de teu coração.", ref: "Provérbios 3:3" },
  { text: "Pois todas as coisas que foram escritas com antecedência foram escritas para o nosso ensino; para que, pela paciência e consolação das Escrituras, tenhamos esperança.", ref: "Romanos 15:4" },
  { text: "Pois com o coração se crê para a justiça, e com a boca se confessa para a salvação.", ref: "Romanos 10:10" },
  { text: "E tal confiança temos por Cristo para com Deus.", ref: "2 Coríntios 3:4" },
  { text: "Louvai ao SENHOR com harpa; cantai louvores a ele com saltério de dez cordas.", ref: "Salmos 33:2" },
  { text: "Servi ao SENHOR com temor; e alegrai-vos com tremor.", ref: "Salmos 2:11" },
  { text: "Por isso, amados, aguardando essas coisas, procurai que por ele sejais achados incontaminados e irrepreensíveis em paz;", ref: "2 Pedro 3:14" },
  { text: "Nem também os que passam, digam: “A bênção do SENHOR seja sobre vós; nós vos bendizemos no nome do SENHOR”.", ref: "Salmos 129:8" },
  { text: "Pois nós nos alegramos quando estamos fracos, e vós estais fortes; e isto também desejamos: o vosso aperfeiçoamento.", ref: "2 Coríntios 13:9" },
  { text: "Uma coisa peço ao SENHOR, e a busco: que eu possa morar na casa do SENHOR todos os dias de minha vida, para contemplar a beleza do SENHOR, e meditar em seu templo.", ref: "Salmos 27:4" },
  { text: "E, depois de ter sido consumado, ele foi feito autor da eterna salvação a todos os que lhe obedecem;", ref: "Hebreus 5:9" },
  { text: "Envia tua luz e tua verdade, para que me guiem e me levem ao teu santo monte, e às tuas moradas.", ref: "Salmos 43:3" },
  { text: "Porque a um é dada, pelo Espírito, palavra de sabedoria; e a outro palavra de conhecimento, pelo mesmo Espírito.", ref: "1 Coríntios 12:8" },
  { text: "Livra-me Deus; apressa-te para me socorrer, SENHOR.", ref: "Salmos 70:1" },
  { text: "Porque tua leal bondade está diante de meus olhos; e ando em tua verdade.", ref: "Salmos 26:3" },
  { text: "Pois como agradecemos a Deus por vós, por toda a alegria com que nos alegramos por vossa causa, diante do nosso Deus!", ref: "1 Tessalonicenses 3:9" },
  { text: "Se algum de vós tem falta de sabedoria, peça a Deus, que concede generosamente a todos sem repreender, e lhe será dada.", ref: "Tiago 1:5" },
  { text: "Cheguemos perante sua presença com ações de graças; celebremos a ele com salmos.", ref: "Salmos 95:2" },
  { text: "O fim do mandamento é o amor que vem de um coração puro, e de uma boa consciência, e de uma fé não fingida.", ref: "1 Timóteo 1:5" },
  { text: "Estando nós ainda mortos em nossas ofensas, nos deu vida juntamente com Cristo (pela graça sois salvos),", ref: "Efésios 2:5" },
  { text: "Para dar inteligência aos simples, conhecimento e bom senso aos jovens.", ref: "Provérbios 1:4" },
  { text: "Levantai, ó portas, vossas cabeças; e levantai-vos, ó entradas eternas; para que entre o Rei da Glória.", ref: "Salmos 24:7" },
  { text: "Portanto, a Lei é santa, e o mandamento é santo, justo, e bom.", ref: "Romanos 7:12" },
  { text: "Tu és mais belo que os filhos dos homens; a graça se derramou em teus lábios, por isso, Deus te abençoou para sempre.", ref: "Salmos 45:2" },
  { text: "Ó SENHOR, meu Deus, são muitas as maravilhas que operaste e teus planos em nosso favor; eles não podem ser listados diante de ti; se eu os tentasse anunciar e deles falar, são mais do que se conseguem contar.", ref: "Salmos 40:5" },
  { text: "Em tudo mostra a ti mesmo como exemplo de boas obras; na doutrina, mostra incorrupção, dignidade, sinceridade;", ref: "Tito 2:7" },
  { text: "Bendize, ó minha alma, ao SENHOR; ó SENHOR meu Deus, tu és muito grandioso; estás vestido de glória e de majestade.", ref: "Salmos 104:1" },
  { text: "A graça do Senhor Jesus Cristo esteja convosco.", ref: "1 Coríntios 16:23" },
  { text: "Aleluia! Dai graças ao SENHOR, porque ele é bom, porque seu leal amor dura para sempre.", ref: "Salmos 106:1" },
  { text: "Oferecei sacrifícios de justiça, e confiai no SENHOR.", ref: "Salmos 4:5" },
  { text: "Lembro-me disto, e derramo minha alma dentro de mim; pois eu ia com a multidão, e com eles me dirigia à casa de Deus, com voz de alegria e louvor, com a multidão que festejava.", ref: "Salmos 42:4" },
  { text: "O temor ao SENHOR é o princípio da sabedoria; e o conhecimento dos santos é a prudência.", ref: "Provérbios 9:10" },
  { text: "E experimentaram a boa palavra de Deus, e os poderes do mundo futuro;", ref: "Hebreus 6:5" },
  { text: "Eu me lembrarei das obras do SENHOR; porque me recordo das tuas maravilhas da antiguidade.", ref: "Salmos 77:11" },
  { text: "Toda a terra te adorará e cantará louvores a ti; cantarão ao teu nome”. (Selá)", ref: "Salmos 66:4" },
  { text: "Quem dentre vós for sábio e inteligente, que mostre pela boa conduta as suas obras em humildade de sabedoria.", ref: "Tiago 3:13" },
  { text: "Os céus anunciam sua justiça, e todos os povos veem sua glória.", ref: "Salmos 97:6" },
  { text: "Bem-aventurado é aquele a quem tu escolhes, e trazes para perto, para que habite em teus átrios; seremos saciados da bondade da tua casa, o teu santo templo.", ref: "Salmos 65:4" },
  { text: "Não retribuais o mal com mal, ou insulto com insulto; ao contrário, bendizei, sabendo que para isto fostes chamados, para que herdeis a bênção.", ref: "1 Pedro 3:9" },
  { text: "Mas amados, desta uma coisa não ignoreis: que um dia para o Senhor é como mil anos, e mil anos como um dia.", ref: "2 Pedro 3:8" },
  { text: "Mas, como fomos aprovados por Deus para que o evangelho nos fosse confiado, assim falamos; não para agradar as pessoas, mas sim a Deus, que prova os nossos corações.", ref: "1 Tessalonicenses 2:4" },
  { text: "Gloriai-vos em seu santo nome; alegre-se o coração dos que buscam o SENHOR.", ref: "Salmos 105:3" },
  { text: "Porque ele diz: Em tempo agradável te ouvi, e no dia da salvação te socorri; eis agora o tempo agradável, eis agora o dia da salvação", ref: "2 Coríntios 6:2" },
  { text: "Pela sabedoria a casa é edificada, e pelo entendimento ela fica firme;", ref: "Provérbios 24:3" },
  { text: "Ele te envie socorro desde o santuário, e te sustenha desde Sião.", ref: "Salmos 20:2" },
  { text: "Agradeço a Deus, a quem desde os meus antepassados sirvo com uma consciência pura, de que sem cessar tenho memória de ti nas minhas orações noite e dia.", ref: "2 Timóteo 1:3" },
  { text: "Pois o que já foi glorioso, em comparação, deixou de ter glória, por causa da glória superior.", ref: "2 Coríntios 3:10" },
  { text: "Bendito seja o SENHOR, que não nos entregou por presa aos dentes deles.", ref: "Salmos 124:6" },
  { text: "Mas sempre devemos dar graças a Deus por vós, irmãos, que sois amados pelo Senhor, pois Deus vos escolheu desde o princípio para a salvação, em santificação do Espírito, e fé na verdade;", ref: "2 Tessalonicenses 2:13" },
  { text: "Minha alma espera somente em Deus; dele vem a minha salvação.", ref: "Salmos 62:1" },
  { text: "Por fim, meus irmãos, fortalecei-vos no Senhor e na força do seu poder.", ref: "Efésios 6:10" },
  { text: "Cantarei sobre a leal bondade e a justiça; a ti, SENHOR, cantarei louvores.", ref: "Salmos 101:1" },
  { text: "Dai graças ao SENHOR, porque ele é bom; porque seu leal amor dura para sempre.", ref: "Salmos 107:1" },
  { text: "Louvarei ao SENHOR em todo tempo; continuamente seu louvor estará em minha boca.", ref: "Salmos 34:1" },
  { text: "Não anulo a graça de Deus; pois, se a justiça é por meio da Lei, logo Cristo morreu por nada.", ref: "Gálatas 2:21" },
  { text: "Sacia-nos de manhã com tua leal bondade, para que jubilemos e nos alegremos todos os nossos dias.", ref: "Salmos 90:14" },
  { text: "Porém eu entrarei em tua casa pela grandeza de tua leal bondade; em temor a ti me inclinarei ao teu santo templo.", ref: "Salmos 5:7" },
  { text: "Agradeço ao meu Deus todas as vezes que me lembro de vós,", ref: "Filipenses 1:3" },
  { text: "Para que teu caminho seja conhecido na terra, e tua salvação, entre todas as nações.", ref: "Salmos 67:2" },
  { text: "Bem-aventurados os que habitam em tua casa; eles te louvarão continuamente. (Selá)", ref: "Salmos 84:4" },
  { text: "Aclamai ao SENHOR, ó filhos de Deus, aclamai ao SENHOR a glória e a força.", ref: "Salmos 29:1" },
  { text: "Em verdade ele nunca se abalará; o justo será lembrado para sempre.", ref: "Salmos 112:6" },
  { text: "Nosso socorro está no nome do SENHOR, que fez o céu e a terra.", ref: "Salmos 124:8" },
  { text: "O SENHOR o sustenta no leito de enfermidade; estando doente de cama, tu o restauras.", ref: "Salmos 41:3" },
  { text: "Mas rejeitamos as coisas vergonhosas que se ocultam, não andando com astúcia nem falsificando a Palavra de Deus, mas, pela manifestação da verdade, recomendamo-nos à consciência de todo ser humano, à vista de Deus.", ref: "2 Coríntios 4:2" },
  { text: "Que pela fé estais guardados no poder de Deus para a salvação, pronta para se revelar no último tempo.", ref: "1 Pedro 1:5" },
  { text: "Com toda humildade e mansidão; com paciência, tolerando uns aos outros em amor.", ref: "Efésios 4:2" },
  { text: "Quando os justos se engrandecem, o povo se alegra; mas quando o perverso domina, o povo geme.", ref: "Provérbios 29:2" },
  { text: "Cantarei as leais bondades do SENHOR para sempre; com minha boca contarei tua fidelidade a todas as gerações.", ref: "Salmos 89:1" },
];

export function verseOfDay(date = new Date()) {
  const start = new Date(date.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((date - start) / 86400000);
  const index = (dayOfYear - 1) % verses.length;
  return verses[index];
}
